# Generated by Django 3.0.5 on 2020-05-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=100)),
                ('Photo', models.ImageField(upload_to='')),
                ('Solution', models.CharField(max_length=300)),
            ],
        ),
    ]
