# Generated by Django 3.0.5 on 2020-05-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_diseases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondisease',
            name='Photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
