# Generated by Django 3.0.5 on 2020-05-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_diseases', '0002_auto_20200504_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondisease',
            name='Photo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
